/* The following code was generated by JFlex 1.6.1 */

package tesserac.parser;
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 1998-2015  Gerwin Klein <lsf@jflex.de>                    *
 * All rights reserved.                                                    *
 *                                                                         *
 * License: BSD                                                            *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* Java 1.2 language lexer specification */

/* Use together with unicode.flex for Unicode preprocesssing */
/* and java12.cup for a Java 1.2 parser                      */

/* Note that this lexer specification is not tuned for speed.
   It is in fact quite slow on integer and floating point literals, 
   because the input is read twice and the methods used to parse
   the numbers are not very fast. 
   For a production quality application (e.g. a Java compiler) 
   this could be optimized */



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/c1621/git/tesserac/src/java/tesserac/parser/java.flex</tt>
 */
public class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\61\1\62\1\1\16\7\4\0\1\3\1\46"+
    "\1\24\1\0\1\6\1\46\1\50\1\25\1\42\1\42\1\5\1\52"+
    "\1\42\1\23\1\21\1\4\1\10\1\16\1\53\1\15\1\54\1\17"+
    "\1\57\1\55\1\56\1\11\1\47\1\42\1\45\1\43\1\44\1\47"+
    "\1\0\3\14\1\60\1\22\1\20\5\6\1\12\13\6\1\13\2\6"+
    "\1\42\1\26\1\42\1\46\1\6\1\0\1\27\1\30\1\34\1\60"+
    "\1\36\1\37\5\6\1\40\1\6\1\41\3\6\1\33\1\31\1\32"+
    "\1\35\2\6\1\13\2\6\1\42\1\51\1\42\1\47\6\7\1\63"+
    "\32\7\2\0\4\6\4\0\1\6\2\0\1\7\7\0\1\6\4\0"+
    "\1\6\5\0\27\6\1\0\37\6\1\0\u01ca\6\4\0\14\6\16\0"+
    "\5\6\7\0\1\6\1\0\1\6\21\0\160\7\5\6\1\0\2\6"+
    "\2\0\4\6\10\0\1\6\1\0\3\6\1\0\1\6\1\0\24\6"+
    "\1\0\123\6\1\0\213\6\1\0\5\7\2\0\236\6\11\0\46\6"+
    "\2\0\1\6\7\0\47\6\7\0\1\6\1\0\55\7\1\0\1\7"+
    "\1\0\2\7\1\0\2\7\1\0\1\7\10\0\33\6\5\0\3\6"+
    "\15\0\5\7\6\0\1\6\4\0\13\7\5\0\53\6\37\7\4\0"+
    "\2\6\1\7\143\6\1\0\1\6\10\7\1\0\6\7\2\6\2\7"+
    "\1\0\4\7\2\6\12\7\3\6\2\0\1\6\17\0\1\7\1\6"+
    "\1\7\36\6\33\7\2\0\131\6\13\7\1\6\16\0\12\7\41\6"+
    "\11\7\2\6\4\0\1\6\5\0\26\6\4\7\1\6\11\7\1\6"+
    "\3\7\1\6\5\7\22\0\31\6\3\7\104\0\1\6\1\0\13\6"+
    "\67\0\33\7\1\0\4\7\66\6\3\7\1\6\22\7\1\6\7\7"+
    "\12\6\2\7\2\0\12\7\1\0\7\6\1\0\7\6\1\0\3\7"+
    "\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0\1\6"+
    "\3\0\4\6\2\0\1\7\1\6\7\7\2\0\2\7\2\0\3\7"+
    "\1\6\10\0\1\7\4\0\2\6\1\0\3\6\2\7\2\0\12\7"+
    "\4\6\7\0\1\6\5\0\3\7\1\0\6\6\4\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\2\6\1\0\2\6\2\0"+
    "\1\7\1\0\5\7\4\0\2\7\2\0\3\7\3\0\1\7\7\0"+
    "\4\6\1\0\1\6\7\0\14\7\3\6\1\7\13\0\3\7\1\0"+
    "\11\6\1\0\3\6\1\0\26\6\1\0\7\6\1\0\2\6\1\0"+
    "\5\6\2\0\1\7\1\6\10\7\1\0\3\7\1\0\3\7\2\0"+
    "\1\6\17\0\2\6\2\7\2\0\12\7\1\0\1\6\17\0\3\7"+
    "\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6"+
    "\1\0\5\6\2\0\1\7\1\6\7\7\2\0\2\7\2\0\3\7"+
    "\10\0\2\7\4\0\2\6\1\0\3\6\2\7\2\0\12\7\1\0"+
    "\1\6\20\0\1\7\1\6\1\0\6\6\3\0\3\6\1\0\4\6"+
    "\3\0\2\6\1\0\1\6\1\0\2\6\3\0\2\6\3\0\3\6"+
    "\3\0\14\6\4\0\5\7\3\0\3\7\1\0\4\7\2\0\1\6"+
    "\6\0\1\7\16\0\12\7\11\0\1\6\7\0\3\7\1\0\10\6"+
    "\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6\3\0\1\6"+
    "\7\7\1\0\3\7\1\0\4\7\7\0\2\7\1\0\2\6\6\0"+
    "\2\6\2\7\2\0\12\7\22\0\2\7\1\0\10\6\1\0\3\6"+
    "\1\0\27\6\1\0\12\6\1\0\5\6\2\0\1\7\1\6\7\7"+
    "\1\0\3\7\1\0\4\7\7\0\2\7\7\0\1\6\1\0\2\6"+
    "\2\7\2\0\12\7\1\0\2\6\17\0\2\7\1\0\10\6\1\0"+
    "\3\6\1\0\51\6\2\0\1\6\7\7\1\0\3\7\1\0\4\7"+
    "\1\6\10\0\1\7\10\0\2\6\2\7\2\0\12\7\12\0\6\6"+
    "\2\0\2\7\1\0\22\6\3\0\30\6\1\0\11\6\1\0\1\6"+
    "\2\0\7\6\3\0\1\7\4\0\6\7\1\0\1\7\1\0\10\7"+
    "\22\0\2\7\15\0\60\6\1\7\2\6\7\7\4\0\10\6\10\7"+
    "\1\0\12\7\47\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6"+
    "\2\0\1\6\6\0\4\6\1\0\7\6\1\0\3\6\1\0\1\6"+
    "\1\0\1\6\2\0\2\6\1\0\4\6\1\7\2\6\6\7\1\0"+
    "\2\7\1\6\2\0\5\6\1\0\1\6\1\0\6\7\2\0\12\7"+
    "\2\0\4\6\40\0\1\6\27\0\2\7\6\0\12\7\13\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\10\6\1\0\44\6\4\0"+
    "\24\7\1\0\2\7\5\6\13\7\1\0\44\7\11\0\1\7\71\0"+
    "\53\6\24\7\1\6\12\7\6\0\6\6\4\7\4\6\3\7\1\6"+
    "\3\7\2\6\7\7\3\6\4\7\15\6\14\7\1\6\17\7\2\0"+
    "\46\6\1\0\1\6\5\0\1\6\2\0\53\6\1\0\u014d\6\1\0"+
    "\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0\51\6\1\0"+
    "\4\6\2\0\41\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0"+
    "\4\6\2\0\17\6\1\0\71\6\1\0\4\6\2\0\103\6\2\0"+
    "\3\7\40\0\20\6\20\0\125\6\14\0\u026c\6\2\0\21\6\1\0"+
    "\32\6\5\0\113\6\3\0\3\6\17\0\15\6\1\0\4\6\3\7"+
    "\13\0\22\6\3\7\13\0\22\6\2\7\14\0\15\6\1\0\3\6"+
    "\1\0\2\7\14\0\64\6\40\7\3\0\1\6\3\0\2\6\1\7"+
    "\2\0\12\7\41\0\3\7\2\0\12\7\6\0\130\6\10\0\51\6"+
    "\1\7\1\6\5\0\106\6\12\0\35\6\3\0\14\7\4\0\14\7"+
    "\12\0\12\7\36\6\2\0\5\6\13\0\54\6\4\0\21\7\7\6"+
    "\2\7\6\0\12\7\46\0\27\6\5\7\4\0\65\6\12\7\1\0"+
    "\35\7\2\0\13\7\6\0\12\7\15\0\1\6\130\0\5\7\57\6"+
    "\21\7\7\6\4\0\12\7\21\0\11\7\14\0\3\7\36\6\15\7"+
    "\2\6\12\7\54\6\16\7\14\0\44\6\24\7\10\0\12\7\3\0"+
    "\3\6\12\7\44\6\122\0\3\7\1\0\25\7\4\6\1\7\4\6"+
    "\3\7\2\6\11\0\300\6\47\7\25\0\4\7\u0116\6\2\0\6\6"+
    "\2\0\46\6\2\0\6\6\2\0\10\6\1\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\37\6\2\0\65\6\1\0\7\6\1\0\1\6"+
    "\3\0\3\6\1\0\7\6\3\0\4\6\2\0\6\6\4\0\15\6"+
    "\5\0\3\6\1\0\7\6\16\0\5\7\30\0\1\61\1\61\5\7"+
    "\20\0\2\6\23\0\1\6\13\0\5\7\5\0\6\7\1\0\1\6"+
    "\15\0\1\6\20\0\15\6\3\0\33\6\25\0\15\7\4\0\1\7"+
    "\3\0\14\7\21\0\1\6\4\0\1\6\2\0\12\6\1\0\1\6"+
    "\3\0\5\6\6\0\1\6\1\0\1\6\1\0\1\6\1\0\4\6"+
    "\1\0\13\6\2\0\4\6\5\0\5\6\4\0\1\6\21\0\51\6"+
    "\u0a77\0\57\6\1\0\57\6\1\0\205\6\6\0\4\6\3\7\2\6"+
    "\14\0\46\6\1\0\1\6\5\0\1\6\2\0\70\6\7\0\1\6"+
    "\17\0\1\7\27\6\11\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\40\7\57\0\1\6\u01d5\0\3\6\31\0\11\6\6\7\1\0\5\6"+
    "\2\0\5\6\4\0\126\6\2\0\2\7\2\0\3\6\1\0\132\6"+
    "\1\0\4\6\5\0\51\6\3\0\136\6\21\0\33\6\65\0\20\6"+
    "\u0200\0\u19b6\6\112\0\u51cd\6\63\0\u048d\6\103\0\56\6\2\0\u010d\6"+
    "\3\0\20\6\12\7\2\6\24\0\57\6\1\7\4\0\12\7\1\0"+
    "\31\6\7\0\1\7\120\6\2\7\45\0\11\6\2\0\147\6\2\0"+
    "\4\6\1\0\4\6\14\0\13\6\115\0\12\6\1\7\3\6\1\7"+
    "\4\6\1\7\27\6\5\7\20\0\1\6\7\0\64\6\14\0\2\7"+
    "\62\6\21\7\13\0\12\7\6\0\22\7\6\6\3\0\1\6\4\0"+
    "\12\7\34\6\10\7\2\0\27\6\15\7\14\0\35\6\3\0\4\7"+
    "\57\6\16\7\16\0\1\6\12\7\46\0\51\6\16\7\11\0\3\6"+
    "\1\7\10\6\2\7\2\0\12\7\6\0\27\6\3\0\1\6\1\7"+
    "\4\0\60\6\1\7\1\6\3\7\2\6\2\7\5\6\2\7\1\6"+
    "\1\7\1\6\30\0\3\6\2\0\13\6\5\7\2\0\3\6\2\7"+
    "\12\0\6\6\2\0\6\6\2\0\6\6\11\0\7\6\1\0\7\6"+
    "\221\0\43\6\10\7\1\0\2\7\2\0\12\7\6\0\u2ba4\6\14\0"+
    "\27\6\4\0\61\6\u2104\0\u016e\6\2\0\152\6\46\0\7\6\14\0"+
    "\5\6\5\0\1\6\1\7\12\6\1\0\15\6\1\0\5\6\1\0"+
    "\1\6\1\0\2\6\1\0\2\6\1\0\154\6\41\0\u016b\6\22\0"+
    "\100\6\2\0\66\6\50\0\15\6\3\0\20\7\20\0\7\7\14\0"+
    "\2\6\30\0\3\6\31\0\1\6\6\0\5\6\1\0\207\6\2\0"+
    "\1\7\4\0\1\6\13\0\12\7\7\0\32\6\4\0\1\6\1\0"+
    "\32\6\13\0\131\6\3\0\6\6\2\0\6\6\2\0\6\6\2\0"+
    "\3\6\3\0\2\6\3\0\2\6\22\0\3\7\4\0\14\6\1\0"+
    "\32\6\1\0\23\6\1\0\2\6\1\0\17\6\2\0\16\6\42\0"+
    "\173\6\105\0\65\6\210\0\1\7\202\0\35\6\3\0\61\6\57\0"+
    "\37\6\21\0\33\6\65\0\36\6\2\0\44\6\4\0\10\6\1\0"+
    "\5\6\52\0\236\6\2\0\12\7\u0356\0\6\6\2\0\1\6\1\0"+
    "\54\6\1\0\2\6\3\0\1\6\2\0\27\6\252\0\26\6\12\0"+
    "\32\6\106\0\70\6\6\0\2\6\100\0\1\6\3\7\1\0\2\7"+
    "\5\0\4\7\4\6\1\0\3\6\1\0\33\6\4\0\3\7\4\0"+
    "\1\7\40\0\35\6\203\0\66\6\12\0\26\6\12\0\23\6\215\0"+
    "\111\6\u03b7\0\3\7\65\6\17\7\37\0\12\7\20\0\3\7\55\6"+
    "\13\7\2\0\1\7\22\0\31\6\7\0\12\7\6\0\3\7\44\6"+
    "\16\7\1\0\12\7\100\0\3\7\60\6\16\7\4\6\13\0\12\7"+
    "\u04a6\0\53\6\15\7\10\0\12\7\u0936\0\u036f\6\221\0\143\6\u0b9d\0"+
    "\u042f\6\u33d1\0\u0239\6\u04c7\0\105\6\13\0\1\6\56\7\20\0\4\7"+
    "\15\6\u4060\0\2\6\u2163\0\5\7\3\0\26\7\2\0\7\7\36\0"+
    "\4\7\224\0\3\7\u01bb\0\125\6\1\0\107\6\1\0\2\6\2\0"+
    "\1\6\2\0\2\6\2\0\4\6\1\0\14\6\1\0\1\6\1\0"+
    "\7\6\1\0\101\6\1\0\4\6\2\0\10\6\1\0\7\6\1\0"+
    "\34\6\1\0\4\6\1\0\5\6\1\0\1\6\3\0\7\6\1\0"+
    "\u0154\6\2\0\31\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0"+
    "\37\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0\37\6\1\0"+
    "\31\6\1\0\10\6\2\0\62\7\u1600\0\4\6\1\0\33\6\1\0"+
    "\2\6\1\0\1\6\2\0\1\6\1\0\12\6\1\0\4\6\1\0"+
    "\1\6\1\0\1\6\6\0\1\6\4\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\3\6\1\0\2\6\1\0\1\6\2\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\2\6\1\0"+
    "\1\6\2\0\4\6\1\0\7\6\1\0\4\6\1\0\4\6\1\0"+
    "\1\6\1\0\12\6\1\0\21\6\5\0\3\6\1\0\5\6\1\0"+
    "\21\6\u1144\0\ua6d7\6\51\0\u1035\6\13\0\336\6\u3fe2\0\u021e\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\7\36\0\140\7\200\0\360\7\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\2\4\1\5\2\6\1\7"+
    "\1\4\1\10\1\11\4\5\1\7\6\4\1\12\2\13"+
    "\1\14\2\1\2\15\1\1\1\16\1\0\1\17\1\20"+
    "\1\21\1\0\3\17\1\22\1\20\1\0\1\23\1\0"+
    "\4\5\1\4\1\24\2\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\12\24\2\16\1\0"+
    "\1\37\2\40\2\17\1\20\2\0\4\5\1\25\1\0"+
    "\1\41\1\0\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\40\2\17\1\0\1\5\1\53"+
    "\1\5\1\54\1\40\2\17\1\0\1\5\1\55\1\40"+
    "\2\17\1\0\1\5\1\40\2\17\1\0\1\5\1\40"+
    "\2\17\1\0\1\56\1\40\2\17\1\0\1\40\2\17"+
    "\2\0\2\17\1\57\1\0\2\17\1\0\2\17\1\0"+
    "\2\17\1\0\2\17\1\0\2\17\1\0\1\17\1\20"+
    "\1\0\5\20";

  private static int [] zzUnpackAction() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\234\0\234\0\u0104"+
    "\0\u0138\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\234\0\234"+
    "\0\u0270\0\u02a4\0\u02d8\0\u030c\0\234\0\u0340\0\u0374\0\234"+
    "\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478\0\234\0\234\0\u04ac"+
    "\0\u04e0\0\u0514\0\234\0\u0548\0\u057c\0\u05b0\0\u05e4\0\u0618"+
    "\0\234\0\u064c\0\u0680\0\u06b4\0\u06e8\0\234\0\u071c\0\u0750"+
    "\0\234\0\u0784\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888\0\234"+
    "\0\u08bc\0\u08f0\0\234\0\234\0\234\0\234\0\234\0\234"+
    "\0\234\0\234\0\234\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4"+
    "\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\234\0\u0b60"+
    "\0\234\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc"+
    "\0\u0d00\0\u0d34\0\u0d68\0\u0d9c\0\234\0\u0958\0\234\0\u0dd0"+
    "\0\234\0\234\0\234\0\234\0\234\0\234\0\234\0\234"+
    "\0\234\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\u016c\0\u0f08"+
    "\0\u016c\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\u016c\0\u1040"+
    "\0\u1074\0\u10a8\0\u10dc\0\u1110\0\u1144\0\u1178\0\u11ac\0\u11e0"+
    "\0\u1214\0\u1248\0\u127c\0\u12b0\0\u12e4\0\u016c\0\u1318\0\u134c"+
    "\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u1450\0\u1484\0\u14b8\0\u14ec"+
    "\0\u1520\0\234\0\u1554\0\u1588\0\u15bc\0\u15f0\0\u1624\0\u1658"+
    "\0\u168c\0\u16c0\0\u16f4\0\u1728\0\u175c\0\u1790\0\u17c4\0\u17f8"+
    "\0\u182c\0\u1860\0\u1894\0\u1894\0\u18c8\0\u18fc\0\u1930\0\u1964"+
    "\0\u1998\0\u19cc";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\4"+
    "\1\13\1\14\3\12\3\14\1\12\1\15\1\12\1\16"+
    "\1\17\1\20\1\4\1\21\2\12\1\22\4\12\1\23"+
    "\1\12\1\24\1\25\1\11\1\26\1\27\1\11\1\30"+
    "\1\31\1\32\1\33\5\14\1\12\1\4\1\7\1\4"+
    "\1\34\1\35\1\36\21\34\1\37\1\34\1\40\35\34"+
    "\1\41\1\42\1\43\22\41\1\4\1\44\35\41\66\0"+
    "\1\6\65\0\1\45\1\46\35\0\1\30\63\0\1\30"+
    "\26\0\13\12\1\0\1\12\4\0\13\12\11\0\6\12"+
    "\2\0\1\12\10\0\1\47\1\50\1\51\1\52\1\0"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\13\0\1\60"+
    "\1\56\1\51\12\0\1\53\2\55\1\50\1\55\1\61"+
    "\13\0\2\14\1\51\2\0\3\14\1\56\1\57\1\60"+
    "\13\0\1\60\1\56\1\51\12\0\5\14\1\61\13\0"+
    "\2\57\3\0\3\57\33\0\5\57\27\0\1\30\17\0"+
    "\1\30\7\0\1\62\16\0\13\12\1\0\1\12\4\0"+
    "\1\12\1\63\11\12\11\0\6\12\2\0\1\12\6\0"+
    "\13\12\1\0\1\12\4\0\4\12\1\64\6\12\11\0"+
    "\6\12\2\0\1\12\6\0\13\12\1\0\1\12\4\0"+
    "\1\65\12\12\11\0\6\12\2\0\1\12\6\0\13\12"+
    "\1\0\1\12\4\0\6\12\1\66\4\12\11\0\6\12"+
    "\2\0\1\12\43\0\1\30\1\67\62\0\1\30\1\0"+
    "\1\11\61\0\1\30\4\0\1\30\56\0\1\30\5\0"+
    "\1\30\55\0\1\30\6\0\1\30\11\0\1\34\2\0"+
    "\21\34\1\0\1\34\1\0\35\34\2\0\1\36\61\0"+
    "\1\70\2\0\5\70\1\71\4\70\2\71\1\72\4\70"+
    "\1\73\1\74\1\75\1\70\1\76\1\70\1\77\1\100"+
    "\3\70\1\101\1\70\1\102\11\70\1\71\2\72\1\70"+
    "\1\72\1\70\30\0\1\103\40\0\1\43\61\0\1\70"+
    "\2\0\5\70\1\104\4\70\2\104\1\105\4\70\1\106"+
    "\1\107\1\110\1\70\1\111\1\70\1\112\1\113\3\70"+
    "\1\114\1\70\1\115\11\70\1\104\2\105\1\70\1\105"+
    "\1\70\3\0\1\45\1\116\1\117\61\45\5\46\1\120"+
    "\56\46\10\0\1\47\1\50\1\121\2\0\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\13\0\1\60\1\56\1\121"+
    "\12\0\1\53\2\55\1\50\1\55\1\61\13\0\2\50"+
    "\3\0\3\50\1\56\1\57\1\60\13\0\1\60\1\56"+
    "\13\0\5\50\1\61\13\0\1\122\1\123\2\0\5\123"+
    "\1\0\1\123\4\0\2\123\3\0\1\123\1\0\2\123"+
    "\13\0\6\123\13\0\1\124\1\50\1\121\2\0\3\124"+
    "\1\56\1\57\1\60\13\0\1\60\1\56\1\121\12\0"+
    "\3\124\1\50\1\124\1\61\13\0\1\55\1\50\1\121"+
    "\2\0\3\55\1\56\1\57\1\60\13\0\1\60\1\56"+
    "\1\121\12\0\3\55\1\50\1\55\1\61\13\0\1\125"+
    "\1\50\1\121\2\0\3\125\1\56\1\57\1\60\13\0"+
    "\1\60\1\56\1\121\12\0\3\125\1\50\1\125\1\61"+
    "\13\0\2\57\3\0\3\57\1\56\1\0\1\60\13\0"+
    "\1\60\1\56\13\0\5\57\1\61\13\0\2\126\3\0"+
    "\3\126\3\0\1\127\26\0\1\127\5\126\22\0\1\130"+
    "\53\0\13\12\1\0\1\12\4\0\2\12\1\131\10\12"+
    "\11\0\6\12\2\0\1\12\6\0\13\12\1\0\1\12"+
    "\4\0\6\12\1\132\4\12\11\0\6\12\2\0\1\12"+
    "\6\0\13\12\1\0\1\12\4\0\11\12\1\133\1\12"+
    "\11\0\6\12\2\0\1\12\6\0\13\12\1\0\1\12"+
    "\4\0\11\12\1\134\1\12\11\0\6\12\2\0\1\12"+
    "\43\0\1\30\1\11\27\0\1\72\4\0\3\72\33\0"+
    "\3\72\1\0\1\72\14\0\1\135\4\0\3\135\33\0"+
    "\3\135\1\0\1\135\14\0\1\136\4\0\3\136\5\0"+
    "\1\137\25\0\3\136\1\0\1\136\14\0\1\140\4\0"+
    "\3\140\5\0\1\137\25\0\3\140\1\0\1\140\31\0"+
    "\1\141\63\0\1\142\63\0\1\143\63\0\1\144\63\0"+
    "\1\145\63\0\1\146\63\0\1\147\63\0\1\150\40\0"+
    "\1\117\61\0\4\46\1\117\1\120\56\46\10\0\1\122"+
    "\1\123\1\151\1\0\5\123\1\0\1\123\4\0\2\123"+
    "\3\0\1\123\1\0\2\123\1\151\12\0\6\123\13\0"+
    "\2\152\1\151\1\0\5\152\1\0\1\152\4\0\2\152"+
    "\3\0\1\152\1\0\2\152\1\151\12\0\6\152\13\0"+
    "\1\153\1\50\1\121\2\0\3\153\1\56\1\57\1\60"+
    "\13\0\1\60\1\56\1\121\12\0\3\153\1\50\1\153"+
    "\1\61\13\0\1\154\1\50\1\121\2\0\3\154\1\56"+
    "\1\57\1\60\13\0\1\60\1\56\1\121\12\0\3\154"+
    "\1\50\1\154\1\61\13\0\2\126\3\0\3\126\1\56"+
    "\16\0\1\56\13\0\5\126\1\61\13\0\2\126\3\0"+
    "\3\126\33\0\5\126\60\0\1\155\15\0\13\12\1\0"+
    "\1\12\4\0\3\12\1\156\7\12\11\0\6\12\2\0"+
    "\1\12\6\0\13\12\1\0\1\12\4\0\7\12\1\157"+
    "\3\12\11\0\6\12\2\0\1\12\6\0\13\12\1\0"+
    "\1\12\4\0\2\12\1\160\10\12\11\0\6\12\2\0"+
    "\1\12\6\0\13\12\1\0\1\12\4\0\11\12\1\161"+
    "\1\12\11\0\6\12\2\0\1\12\25\0\1\137\46\0"+
    "\2\162\1\151\1\0\5\162\1\0\1\162\4\0\2\162"+
    "\3\0\1\162\1\0\2\162\1\151\12\0\6\162\13\0"+
    "\1\163\1\50\1\121\2\0\3\163\1\56\1\57\1\60"+
    "\13\0\1\60\1\56\1\121\12\0\3\163\1\50\1\163"+
    "\1\61\13\0\1\164\1\50\1\121\2\0\3\164\1\56"+
    "\1\57\1\60\13\0\1\60\1\56\1\121\12\0\3\164"+
    "\1\50\1\164\1\61\60\0\1\165\14\0\13\12\1\0"+
    "\1\12\4\0\4\12\1\166\6\12\11\0\6\12\2\0"+
    "\1\12\6\0\13\12\1\0\1\12\4\0\7\12\1\167"+
    "\3\12\11\0\6\12\2\0\1\12\10\0\2\170\1\151"+
    "\1\0\5\170\1\0\1\170\4\0\2\170\3\0\1\170"+
    "\1\0\2\170\1\151\12\0\6\170\13\0\1\171\1\50"+
    "\1\121\2\0\3\171\1\56\1\57\1\60\13\0\1\60"+
    "\1\56\1\121\12\0\3\171\1\50\1\171\1\61\13\0"+
    "\1\172\1\50\1\121\2\0\3\172\1\56\1\57\1\60"+
    "\13\0\1\60\1\56\1\121\12\0\3\172\1\50\1\172"+
    "\1\61\57\0\1\173\15\0\13\12\1\0\1\12\4\0"+
    "\1\174\12\12\11\0\6\12\2\0\1\12\10\0\2\175"+
    "\1\151\1\0\5\175\1\0\1\175\4\0\2\175\3\0"+
    "\1\175\1\0\2\175\1\151\12\0\6\175\13\0\1\176"+
    "\1\50\1\121\2\0\3\176\1\56\1\57\1\60\13\0"+
    "\1\60\1\56\1\121\12\0\3\176\1\50\1\176\1\61"+
    "\13\0\1\177\1\50\1\121\2\0\3\177\1\56\1\57"+
    "\1\60\13\0\1\60\1\56\1\121\12\0\3\177\1\50"+
    "\1\177\1\61\61\0\1\200\13\0\13\12\1\0\1\12"+
    "\4\0\5\12\1\201\5\12\11\0\6\12\2\0\1\12"+
    "\10\0\2\202\1\151\1\0\5\202\1\0\1\202\4\0"+
    "\2\202\3\0\1\202\1\0\2\202\1\151\12\0\6\202"+
    "\13\0\1\203\1\50\1\121\2\0\3\203\1\56\1\57"+
    "\1\60\13\0\1\60\1\56\1\121\12\0\3\203\1\50"+
    "\1\203\1\61\13\0\1\204\1\50\1\121\2\0\3\204"+
    "\1\56\1\57\1\60\13\0\1\60\1\56\1\121\12\0"+
    "\3\204\1\50\1\204\1\61\20\0\1\205\54\0\13\12"+
    "\1\0\1\12\4\0\3\12\1\206\7\12\11\0\6\12"+
    "\2\0\1\12\10\0\2\207\1\151\1\0\5\207\1\0"+
    "\1\207\4\0\2\207\3\0\1\207\1\0\2\207\1\151"+
    "\12\0\6\207\13\0\1\210\1\50\1\121\2\0\3\210"+
    "\1\56\1\57\1\60\13\0\1\60\1\56\1\121\12\0"+
    "\3\210\1\50\1\210\1\61\13\0\1\211\1\50\1\121"+
    "\2\0\3\211\1\56\1\57\1\60\13\0\1\60\1\56"+
    "\1\121\12\0\3\211\1\50\1\211\1\61\62\0\1\212"+
    "\14\0\2\213\1\151\1\0\5\213\1\0\1\213\4\0"+
    "\2\213\3\0\1\213\1\0\2\213\1\151\12\0\6\213"+
    "\13\0\1\214\1\50\1\121\2\0\3\214\1\56\1\57"+
    "\1\60\13\0\1\60\1\56\1\121\12\0\3\214\1\50"+
    "\1\214\1\61\13\0\1\215\1\50\1\121\2\0\3\215"+
    "\1\56\1\57\1\60\13\0\1\60\1\56\1\121\12\0"+
    "\3\215\1\50\1\215\1\61\57\0\1\216\17\0\2\217"+
    "\1\151\1\0\5\217\1\0\1\217\4\0\2\217\3\0"+
    "\1\217\1\0\2\217\1\151\12\0\6\217\13\0\1\220"+
    "\1\50\1\121\2\0\3\220\1\56\1\57\1\60\13\0"+
    "\1\60\1\56\1\121\12\0\3\220\1\50\1\220\1\61"+
    "\13\0\1\221\1\50\1\121\2\0\3\221\1\56\1\57"+
    "\1\60\13\0\1\60\1\56\1\121\12\0\3\221\1\50"+
    "\1\221\1\61\61\0\1\222\15\0\2\223\1\151\1\0"+
    "\5\223\1\0\1\223\4\0\2\223\3\0\1\223\1\0"+
    "\2\223\1\151\12\0\6\223\13\0\1\224\1\50\1\121"+
    "\2\0\3\224\1\56\1\57\1\60\13\0\1\60\1\56"+
    "\1\121\12\0\3\224\1\50\1\224\1\61\13\0\1\225"+
    "\1\50\1\121\2\0\3\225\1\56\1\57\1\60\13\0"+
    "\1\60\1\56\1\121\12\0\3\225\1\50\1\225\1\61"+
    "\13\0\2\226\1\151\1\0\5\226\1\0\1\226\4\0"+
    "\2\226\3\0\1\226\1\0\2\226\1\151\12\0\6\226"+
    "\13\0\1\227\1\50\1\121\2\0\3\227\1\56\1\57"+
    "\1\60\13\0\1\60\1\56\1\121\12\0\3\227\1\50"+
    "\1\227\1\61\13\0\1\230\1\50\1\121\2\0\3\230"+
    "\1\56\1\57\1\60\13\0\1\60\1\56\1\121\12\0"+
    "\3\230\1\50\1\230\1\61\13\0\2\231\1\151\1\0"+
    "\5\231\1\0\1\231\4\0\2\231\3\0\1\231\1\0"+
    "\2\231\1\151\12\0\6\231\13\0\1\232\1\50\1\121"+
    "\2\0\3\232\1\56\1\57\1\60\13\0\1\60\1\56"+
    "\1\121\12\0\3\232\1\50\1\232\1\61\13\0\1\233"+
    "\1\50\1\121\2\0\3\233\1\56\1\57\1\60\13\0"+
    "\1\60\1\56\1\121\12\0\3\233\1\50\1\233\1\61"+
    "\13\0\2\234\1\151\1\0\5\234\1\0\1\234\4\0"+
    "\2\234\3\0\1\234\1\0\2\234\1\151\12\0\6\234"+
    "\13\0\1\235\1\50\1\121\2\0\3\235\1\56\1\57"+
    "\1\60\13\0\1\60\1\56\1\121\12\0\3\235\1\50"+
    "\1\235\1\61\13\0\1\236\1\50\1\121\2\0\3\236"+
    "\1\56\1\57\1\60\13\0\1\60\1\56\1\121\12\0"+
    "\3\236\1\50\1\236\1\61\13\0\2\237\1\151\1\0"+
    "\5\237\1\0\1\237\4\0\2\237\3\0\1\237\1\0"+
    "\2\237\1\151\12\0\6\237\13\0\1\240\1\50\1\121"+
    "\2\0\3\240\1\56\1\57\1\60\13\0\1\60\1\56"+
    "\1\121\12\0\3\240\1\50\1\240\1\61\13\0\1\241"+
    "\1\50\1\121\2\0\3\241\1\56\1\57\1\60\13\0"+
    "\1\60\1\56\1\121\12\0\3\241\1\50\1\241\1\61"+
    "\13\0\2\242\1\151\1\0\5\242\1\0\1\242\4\0"+
    "\2\242\3\0\1\242\1\0\2\242\1\151\12\0\6\242"+
    "\13\0\1\243\1\50\1\121\2\0\3\243\1\56\1\57"+
    "\1\60\13\0\1\60\1\56\1\121\12\0\3\243\1\50"+
    "\1\243\1\61\13\0\1\244\1\50\1\121\2\0\3\244"+
    "\1\56\1\57\1\60\13\0\1\60\1\56\1\121\12\0"+
    "\3\244\1\50\1\244\1\61\13\0\2\245\1\151\1\0"+
    "\5\245\1\0\1\245\4\0\2\245\3\0\1\245\1\0"+
    "\2\245\1\151\12\0\6\245\13\0\1\246\1\50\1\121"+
    "\2\0\3\246\1\56\1\57\1\60\13\0\1\60\1\56"+
    "\1\121\12\0\3\246\1\50\1\246\1\61\15\0\1\151"+
    "\25\0\1\151\33\0\1\247\1\50\1\121\2\0\3\247"+
    "\1\56\1\57\1\60\13\0\1\60\1\56\1\121\12\0"+
    "\3\247\1\50\1\247\1\61\13\0\1\250\1\50\1\121"+
    "\2\0\3\250\1\56\1\57\1\60\13\0\1\60\1\56"+
    "\1\121\12\0\3\250\1\50\1\250\1\61\13\0\1\251"+
    "\1\50\1\121\2\0\3\251\1\56\1\57\1\60\13\0"+
    "\1\60\1\56\1\121\12\0\3\251\1\50\1\251\1\61"+
    "\13\0\1\252\1\50\1\121\2\0\3\252\1\56\1\57"+
    "\1\60\13\0\1\60\1\56\1\121\12\0\3\252\1\50"+
    "\1\252\1\61\13\0\2\50\1\121\2\0\3\50\1\56"+
    "\1\57\1\60\13\0\1\60\1\56\1\121\12\0\5\50"+
    "\1\61\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6656];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\2\11\7\1\2\11\4\1\1\11"+
    "\2\1\1\11\5\1\2\11\3\1\1\11\2\1\1\0"+
    "\2\1\1\11\1\0\3\1\1\11\1\1\1\0\1\11"+
    "\1\0\5\1\1\11\2\1\11\11\13\1\1\11\1\0"+
    "\1\11\5\1\2\0\4\1\1\11\1\0\1\11\1\0"+
    "\11\11\3\1\1\0\7\1\1\0\5\1\1\0\4\1"+
    "\1\0\4\1\1\0\4\1\1\0\3\1\2\0\2\1"+
    "\1\11\1\0\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuilder string = new StringBuilder();
  
  private Symbol symbol(TokenType type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(TokenType type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }

  /** 
   * assumes correct representation of a long value for 
   * specified radix in scanner buffer from <code>start</code> 
   * to <code>end</code> 
   */
  private long parseLong(int start, int end, int radix) {
    long result = 0;
    long digit;

    for (int i = start; i < end; i++) {
      digit  = Character.digit(yycharat(i),radix);
      result*= radix;
      result+= digit;
    }

    return result;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2878) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Illegal character \""+yytext()+
                                                              "\" at line "+yyline+", column "+yycolumn);
            }
          case 48: break;
          case 2: 
            { return symbol(TokenType.LineTerminator);
            }
          case 49: break;
          case 3: 
            { return symbol(TokenType.WhitesSpace,yytext());
            }
          case 50: break;
          case 4: 
            { return symbol(TokenType.Operator,yytext());
            }
          case 51: break;
          case 5: 
            { return symbol(TokenType.Identifier, yytext());
            }
          case 52: break;
          case 6: 
            { return symbol(TokenType.Literal, new Integer(yytext()));
            }
          case 53: break;
          case 7: 
            { return symbol(TokenType.Separator,yytext());
            }
          case 54: break;
          case 8: 
            { yybegin(STRING); string.setLength(0);
            }
          case 55: break;
          case 9: 
            { yybegin(CHARLITERAL);
            }
          case 56: break;
          case 10: 
            { string.append( yytext() );
            }
          case 57: break;
          case 11: 
            { throw new RuntimeException("Unterminated string at end of line");
            }
          case 58: break;
          case 12: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, string.toString());
            }
          case 59: break;
          case 13: 
            { throw new RuntimeException("Unterminated character literal at end of line");
            }
          case 60: break;
          case 14: 
            { /* ignore */
            }
          case 61: break;
          case 15: 
            { return symbol(TokenType.Literal, new Integer((int) parseLong(0, yylength(), 8)));
            }
          case 62: break;
          case 16: 
            { return symbol(TokenType.Literal, new Double(yytext()));
            }
          case 63: break;
          case 17: 
            { return symbol(TokenType.Literal, new Long(yytext().substring(0,yylength()-1)));
            }
          case 64: break;
          case 18: 
            { return symbol(TokenType.Literal, new Float(yytext().substring(0,yylength()-1)));
            }
          case 65: break;
          case 19: 
            { return symbol(TokenType.Literal, new Double(yytext().substring(0,yylength()-1)));
            }
          case 66: break;
          case 20: 
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            }
          case 67: break;
          case 21: 
            { char val = (char) Integer.parseInt(yytext().substring(1),8);
                        				   string.append( val );
            }
          case 68: break;
          case 22: 
            { string.append( '\"' );
            }
          case 69: break;
          case 23: 
            { string.append( '\'' );
            }
          case 70: break;
          case 24: 
            { string.append( '\\' );
            }
          case 71: break;
          case 25: 
            { string.append( '\b' );
            }
          case 72: break;
          case 26: 
            { string.append( '\t' );
            }
          case 73: break;
          case 27: 
            { string.append( '\r' );
            }
          case 74: break;
          case 28: 
            { string.append( '\f' );
            }
          case 75: break;
          case 29: 
            { string.append( '\n' );
            }
          case 76: break;
          case 30: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, yytext().charAt(0));
            }
          case 77: break;
          case 31: 
            { return symbol(TokenType.Literal, new Long(parseLong(0, yylength()-1, 8)));
            }
          case 78: break;
          case 32: 
            { return symbol(TokenType.Literal, new Integer((int) parseLong(2, yylength(), 16)));
            }
          case 79: break;
          case 33: 
            { yybegin(YYINITIAL); 
			                              int val = Integer.parseInt(yytext().substring(1,yylength()-1),8);
			                            return symbol(TokenType.Literal, (char)val);
            }
          case 80: break;
          case 34: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, '\"');
            }
          case 81: break;
          case 35: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, '\'');
            }
          case 82: break;
          case 36: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, '\\');
            }
          case 83: break;
          case 37: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, '\b');
            }
          case 84: break;
          case 38: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, '\t');
            }
          case 85: break;
          case 39: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, '\r');
            }
          case 86: break;
          case 40: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, '\f');
            }
          case 87: break;
          case 41: 
            { yybegin(YYINITIAL); return symbol(TokenType.Literal, '\n');
            }
          case 88: break;
          case 42: 
            { return symbol(TokenType.Literal, new Long(parseLong(2, yylength()-1, 16)));
            }
          case 89: break;
          case 43: 
            { return symbol(TokenType.Literal, true);
            }
          case 90: break;
          case 44: 
            { return symbol(TokenType.Literal,null);
            }
          case 91: break;
          case 45: 
            { return symbol(TokenType.Literal, false);
            }
          case 92: break;
          case 46: 
            { return symbol(TokenType.Keyword,yytext());
            }
          case 93: break;
          case 47: 
            { return symbol(TokenType.Literal, new Integer(Integer.MIN_VALUE));
            }
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
